### ISSUE TITLE
[Feature Repuest] 能否给fcitx5-Rime也增加单行模式

### ISSUE THREAD

**Issue by hosxy** [fcitx/fcitx5-rime#1]
能否像拼音输入法一样，也给 fcitx5-Rime 也增加单行模式，就像拼音输入法的issue3 [#3](https://github.com/fcitx/fcitx5-chinese-addons/issues/3)

**Comment by lowy** [comment]
+1

**Comment by imaojun** [comment]
Strong support. Please add this feature.
