### ISSUE TITLE
用户词库无法同步

### ISSUE THREAD

**Issue by jianghuiwen2018** [fcitx/fcitx5-rime#11]
## 用户词库无法同步
* 使用自定义的输入法方案时，运行`rime_deployer --build ~/.local/share/fcitx5/rime/` 命令布署rime,没有报错，输入法正常运行，但是之前的用户词库无法同步。
## 无法自动加载`/usr/share/rime-data/` 中的共享文件
```bash
rime_deployer --build ~/.local/share/fcitx5/rime/                                                                  
E0817 17:03:53.806800 13605 config_compiler.cc:428] resource could not be loaded: symbols
E0817 17:03:53.806860 13605 legacy_preset_config_plugin.cc:56] failed to include section symbols:punctuator
E0817 17:03:53.806879 13605 config_component.cc:250] error building config: uggx.schema
E0817 17:03:53.844048 13605 config_compiler.cc:428] resource could not be loaded: symbols
E0817 17:03:53.844079 13605 legacy_preset_config_plugin.cc:56] failed to include section symbols:punctuator
E0817 17:03:53.844110 13605 config_component.cc:250] error building config: pinyin_simp.schema
E0817 17:03:53.948621 13605 config_compiler.cc:428] resource could not be loaded: symbols
E0817 17:03:53.948640 13605 legacy_preset_config_plugin.cc:56] failed to include section symbols:punctuator
E0817 17:03:53.948688 13605 config_component.cc:250] error building config: uggx_fluency.schema
```
* `symbols.yaml`,`default.yaml`等共享文件需要手动从`/usr/share/rime-data`复制到`~/.local/share/fcitx5-rime`,无法自动加载

**Comment by whriedplanck** [comment]
会不会是权限问题，加 `sudo` 尝试一下先。

**Comment by whriedplanck** [comment]
> 会不会是权限问题，加 `sudo` 尝试一下先。

这个答案可能看起来有点不靠谱，但在我这有时候能解决一些奇怪的问题。
如果没能解决的话，看起来是 `symbols.yaml` 的 `punctuator` 部分有点问题，考虑到你自定义了方案，会不会是笔误造成了语法问题？

**Comment by wengxt** [comment]
我不用rime，但是你是不是应该在 fcitx 运行的时候点击界面那个重新部署啊？

**Comment by jianghuiwen2018** [comment]
Hi, 抱歉回复晚了。
测试结果：sudo 命令依然无法自动加载系统共享文件以及同步用户词库。
同时发现另一个有意思的问题：
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 这是我目前使用的郑码输入法方案：https://github.com/X1aomu/rime-uggx。因为fcitx5-rime无法同步我之前的词库，所以转而使用ibus-rime平台，该方案在ibus-rime下表现良好（能够同步词库及自动加载共享文件）。但在执行ibus_deplodyer --build ~/.config/ibus/rime 命令时仍然报出如下错误：
E0826 00:36:58.165858 13713 config_compiler.cc:428] resource could not be loaded: pinyin_simp.schema
也就是依然无法加载我在/usr/share/rime-data 目录中的共享文件(尽管整个方案表现正常)。
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 所以我猜测是不是rime_deployer 该命令本身有问题....





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5-rime"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月18日(星期二) 中午12:04
收件人:&nbsp;"fcitx/fcitx5-rime"<fcitx5-rime@noreply.github.com&gt;;
抄送:&nbsp;"Zhengyuan"<1497911983@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fcitx/fcitx5-rime] 用户词库无法同步 (#11)





  
会不会是权限问题，加 sudo 尝试一下先。
  
这个答案可能看起来有点不靠谱，但在我这有时候能解决一些奇怪的问题。
 如果没能解决的话，看起来是 symbols.yaml 的 punctuator 部分有点问题，考虑到你自定义了方案，会不会是笔误造成了语法问题？

**Comment by jianghuiwen2018** [comment]
gnome平台在fcitx-rime下有部署按钮，在fcitx5-rime下没有部署按钮吧





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5-rime"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 凌晨0:43
收件人:&nbsp;"fcitx/fcitx5-rime"<fcitx5-rime@noreply.github.com&gt;;
抄送:&nbsp;"Zhengyuan"<1497911983@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fcitx/fcitx5-rime] 用户词库无法同步 (#11)





 
我不用rime，但是你是不是应该在 fcitx 运行的时候点击界面那个重新部署啊？

**Comment by jianghuiwen2018** [comment]
Hi,我重读了archwiki，该问题在最新的fcitx5下已完美解决，布署及同步按钮都有了，均正常运行，thanks !





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fcitx/fcitx5-rime"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 凌晨0:43
收件人:&nbsp;"fcitx/fcitx5-rime"<fcitx5-rime@noreply.github.com&gt;;
抄送:&nbsp;"Zhengyuan"<1497911983@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fcitx/fcitx5-rime] 用户词库无法同步 (#11)





 
我不用rime，但是你是不是应该在 fcitx 运行的时候点击界面那个重新部署啊？
