### ISSUE TITLE
在fcitx5-rime把共享状态关了，也还是会一直共享，另外app_options设置也无效

### ISSUE THREAD

**Issue by marsjane** [fcitx/fcitx5-rime#115]
我和 #101 一样，在fcitx5-rime把共享状态关了，也还是会一直共享，另外app_options设置也无效，fcitx5-rime 版本：
`local/fcitx5-rime 5.1.8-1`

**Comment by wengxt** [comment]
@marsjane 什么桌面环境

**Comment by marsjane** [comment]
OS 是arch: EndeavourOS Linux x86_64 ，WM: i3

**Comment by wengxt** [comment]
@marsjane 你先去rime自己设置里看看

**Comment by wengxt** [comment]
@marsjane rime设置里现在有一个独立控制rime的状态的选项，默认是全局

**Comment by marsjane** [comment]
我找了半天也没找到那个设置哎，能指点一下是哪个么，另外我还试了直接把默认的状态设置成英文也好像是没有效果的，现在就是一直是一个开启的时候默认中文，然后全局切换，我的设置好像都没有用。目前的设置主要如下：

```
 > cat rime_ice.custom.yaml
patch:
  "switches/@0/reset": 1
```
```
> cat default.custom.yaml
patch:
  schema_list:
    - schema: rime_ice               # 雾凇拼音（全拼）

  app_options/com.apple.Xcode:
    ascii_mode: true
  app_options/com.alfredapp.Alfred:
    ascii_mode: true
  app_options/Alacritty:
    ascii_mode: true

```

**Comment by marsjane** [comment]
![image](https://github.com/fcitx/fcitx5-rime/assets/45665172/87cc42f8-99a0-4383-8df1-5258ce0fd488)
这是Fcitx5的设置

**Comment by marsjane** [comment]
我把那个Reset state on Focus in 换成All也是一样

**Comment by marsjane** [comment]
试了一下这个https://github.com/fcitx/fcitx5-rime/blob/master/data/fcitx5.yaml
好像也没有变化
```
> cat fcitx5.yaml
# Fcitx5 settings
# encoding: utf-8

config_version: "0.22"

# set app options based on app name
# e.g.
# "app_options/kwrite":
#   - ascii_mode: true
# You may obtain the app name via
# dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
"app_options/alacritty":
  - ascii_mode: true
```

**Comment by wengxt** [comment]
![image](https://github.com/fcitx/fcitx5-rime/assets/259684/84be5056-a928-4202-a098-2e5ced5900dd)
我说的是这个配置

**Comment by mao-yining** [comment]
cosmic-workspaces 1.0.12 在配置后还是无效。

---

fcitx本身的配置针对非rime的输入法也无法设置不共享。

**Comment by wengxt** [comment]
fcitx用wayland协议时需要别的方式获得当前窗口是什么

目前只支持 plasma_window_management, 还有 wlr-foreign-toplevel-management 两个协议获得窗口是什么

**Comment by wengxt** [comment]
看起来有一个新协议  foreign_toplevel_list 可以拿来用一下
