### ISSUE TITLE
fcitx5.yaml的app_options设置不起作用

### ISSUE THREAD

**Issue by rtransformation** [fcitx/fcitx5-rime#116]
/usr/share/rime-data下有一个模板fcitx5.yaml文件，如下：

```
# Fcitx5 settings
# encoding: utf-8

config_version: "0.22"

# set app options based on app name
# e.g.
# "app_options/kwrite":
#   - ascii_mode: true
# You may obtain the app name via
# dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo

```
我尝试在这个文件下加：

```
"app_options/konsole":
  - ascii_mode: true
```
或在~/.local/share/fcitx5/rime下的fcitx5.custom.yaml设置相同的内容，都不起作用。
我用的是Arch Linux。之前用debian12的时候是好使的，忘了是什么版本的软件了，手头没有debian12了现在。但debian12上的rime版本应该没有arch上这么新。
另外朋友最近用win11安了最新版的小狼毫，在weasel.yaml里设置这些内容也不起作用。

OS: [Arch Linux]
Version: [fcitx5-5.1.10]

**Comment by wengxt** [comment]
你需要先把 fcitx5-rime 设置当中的状态共享选项修改一下。否则状态本来就是共享的，也就没有 app_options 起作用的余地了
