### ISSUE TITLE
如何关闭候选框内显示的拼音？

### ISSUE THREAD

**Issue by Yikai-Liao** [fcitx/fcitx5-rime#120]
![屏幕截图_20240907_143228](https://github.com/user-attachments/assets/5a64d657-0195-479f-a908-2d9accb2d726)
![屏幕截图_20240907_144120](https://github.com/user-attachments/assets/998d48c3-7bfb-4d66-9689-2c8edc4a3f61)

我之前在 debian Ubuntu arch等系统（Plasma 5 / Plasma 6）都在使用fcitx5 + rime，并使用 rime-ice 配置。我正在尝试将我的系统切换到openSUSE，但是在配置好输入法后出现了图中的情况。我没能从Google 中直接查找到这种情况对应的配置文件中的哪一项。而且我觉得这可能不是配置文件的问题？因为我的配置文件与我正在使用KDE6的kde neon系统中的配置文件保持一致（只调整了rime-ice 默认配置文件中的候选项数量）。

不过，fcitx5 中的拼音 输入法是不会显示候选项拼音的，因此我仍然无法定位到问题出在哪里，所以我想在这里请求帮助。

**Comment by ksqsf** [comment]
> 我没能从Google 中直接查找到这种情况对应的配置文件中的哪一项。而且我觉得这可能不是配置文件的问题？

请检查 spelling_hints 和 comment_format

**Comment by Yikai-Liao** [comment]
解决了，感谢🙏

**Comment by AClon314** [comment]
> 解决了，感谢🙏

@Yikai-Liao 请问是如何解决的？

**Comment by AClon314** [comment]
在 [rime_ice.schema.yaml](https://github.com/iDvel/rime-ice/blob/65f915247295ca8097d29f36afa2927740558c7a/rime_ice.schema.yaml#L290) 中，设置为`spelling_hints: 0`即可。
