### ISSUE TITLE
更新fcitx5之后rime提示不可用了

### ISSUE THREAD

**Issue by Goopher97** [fcitx/fcitx5-rime#125]
系统是ubuntu24.04，fcitx5和rime都是通过flatpak安装的。fcitx5版本5.1.11，rime版本5.1.9，切换rime提示中州韵（不可用）。

**Comment by wengxt** [comment]
flatpak 还没更新完全，你可以考虑装unstable的或者等一等

https://fcitx-im.org/wiki/Install_Fcitx_5#Install_Fcitx_5_from_Flatpak

Goopher97 ***@***.***> 于 2024年11月9日周六 07:53写道：

**Comment by Goopher97** [comment]
感谢回复 我再等等

**Comment by wengxt** [comment]
更新应该就可以了
