### ISSUE TITLE
请问rime在fcitx5中不能shift上屏吗？

### ISSUE THREAD

**Issue by shi429101906** [fcitx/fcitx5-rime#13]
拼音可以左shift切换上屏， rime不行， 但是同样的配置在ibus是可以上屏的， 是不是fcitx5中的什么配置把rime的上屏给覆盖了呢？

**Comment by shi429101906** [comment]
之前左shift是不能上屏的，切换之后会自动将文字给丢掉， 今天新加了功能取消激活输入法时提交当前文本可以上屏了， 但是提交的是中文， 也不是我想要的...... 之前的配置在ibus是好好的， 实在不知道要怎么搞了

**Comment by shi429101906** [comment]
> fcitx的左移默认是切换输入法。
之前左移是不能上屏的，切换之后会自动将文字给丢掉，今天新加了功能取消激活输入法时提交当前文本可以上屏了，但是提交的是中文，也不是我想要的.. ....之前的配置在ibus是好好的，实在不知道要怎么搞了

**Comment by shi429101906** [comment]
最气的是， fcitx5的拼音就可以>_<

**Comment by wengxt** [comment]
你可以设置去掉那个 shift 按键转成用 rime 的功能

**Comment by shi429101906** [comment]
> 你可以设置去掉那个 shift 按键转成用 rime 的功能

这个快捷键在linux里用习惯了， ctrl+space手册切换， shift快捷切换。 要是操作习惯比较好改的话我就不会这么纠结了><

**Comment by shi429101906** [comment]
> 你可以设置去掉那个 shift 按键转成用 rime 的功能

大佬， 如果我去掉shift快捷切换输入法， fcitx5的图标可以切换吗？ 像ibus那样最少得让我知道当前是英文还是中文啊， 
ibus会显示 “朙” 或者 “A” 来区分中英文， 小狼毫会显示 “中” 或者 “英”， 而fcitx5-rime中只有rime自己的图标
