### ISSUE TITLE
请问如何删除自造词？

### ISSUE THREAD

**Issue by cyqsimon** [fcitx/fcitx5-rime#130]
看过了[ArchWiki](https://wiki.archlinuxcn.org/wiki/Fcitx5)与众多其他资源，未能找到可用的删词快捷键或相关选项。

以下均无效：
- <kbd>ctrl</kbd><kbd>del</kbd>
- <kbd>shift</kbd><kbd>del</kbd>
- <kbd>ctrl</kbd><kbd>shift</kbd><kbd>del</kbd>
- <kbd>alt</kbd><kbd>del</kbd>
- <kbd>ctrl</kbd><kbd>7</kbd>

请问是否有此功能？若无请视作 feature request，谢谢。

**Comment by eagleoflqj** [comment]
rime默认的删词快捷键是ctrl+delete或者shift+delete，需要先把高亮移动到待删的词上面。删不掉的话要么是你的配置把键改掉了，要么是这个词本来就在dict.yaml里，删词只能起到重置频率的效果。总之不是这个仓库的问题。

**Comment by cyqsimon** [comment]
感谢秒回。

我去确认了一下，确实如你所说，我想删除的词语存在于包管理器的默认词库中：

```bash
$ rg -l MY_WORD /usr/share/rime-data
/usr/share/rime-data/essay.txt
```

由于该词的罕见性，我误以为是自造词并以为删除键无效。刚才测试后发现其实<kbd>ctrl</kbd><kbd>del</kbd>与<kbd>shift</kbd><kbd>del</kbd>在真正的自造词上都可用。

顺便问下，这种系统词库内的词汇我不希望显示的情况，是否支持通过用户配置将其mask掉？还是说只能去修改系统词库本身？

**Comment by eagleoflqj** [comment]
你可以试试在用户目录 ~/.local/share/fcitx5/rime 准备一份去掉那个词的 essay.txt 重新部署。
如果不行，可以换其他不使用自带 essay.txt 的rime方案。
