### ISSUE TITLE
unable to switch 'ascii mode' in Ghostty

### ISSUE THREAD

**Issue by haolian9** [fcitx/fcitx5-rime#131]
hi, i found that the `shift` key has no effect in Ghostty with fcitx5-rime IME which is supposed to switch 'ascii mode' of Rime.
as a constrast, i added `shuangpin` to fcitx5's input methods. it works well, which makes me belive that it's not a problem on Ghostty side, but just fcitx5-rime does not response the `shift` key.

![2952872c-c592-11ef-8cc5-b881989529be](https://github.com/user-attachments/assets/11adc9b2-57f7-4aea-ae63-d8610d57add6)

**Comment by wengxt** [comment]
it's a bug in ghostty.

https://github.com/ghostty-org/ghostty/discussions/3628#discussioncomment-11688161
