### ISSUE TITLE
希望可以左shift上屏, 然后切换英文

### ISSUE THREAD

**Issue by yangshann** [fcitx/fcitx5-rime#15]
fcitx5-rime在输入法内切换中英文可以实现上屏,但在rime和'键盘-英语'输入法间切换的时候却并不能像fcitx5-chinese-addons中拼音那样左shift上屏然后切换成英文

**Comment by wengxt** [comment]
这个没办法做到。另外的方式就是你把fcitx 配置里面的 shift 去掉，这样 rime 自己会接管处理。

**Comment by puzzle9** [comment]
改配置按键吧

`default.custom.yaml`

```yaml
patch:
  ascii_composer/switch_key/Shift_L: commit_code
```

<https://github.com/rime/home/issues/790>

**Comment by dhay3** [comment]
Greeting fcitx5-rime maintainers,

Sorry to dig this thread, it seems someone has implemented that feature in PR #118 . It would be great if it merge into the master branch.

Best regards
