### ISSUE TITLE
怎么加载 librime-lua 插件?

### ISSUE THREAD

**Issue by yar999** [fcitx/fcitx5-rime#16]
我本地是manjaro环境,我看到 fcitx5-rime 的配置项里面可以配置 插件和模块了
但是不管在插件还是在模块那里添加 `/usr/lib/librime-lua.so` 都无法成功

还是提示下面的错误:
E0925 12:22:21.684703 30740 engine.cc:349] error creating translator: 'lua_translator'

**Comment by wengxt** [comment]
配置成這樣
<img width="358" alt="图片" src="https://user-images.githubusercontent.com/259684/94475517-08360180-0184-11eb-859e-d74a01c862cd.png">

**Comment by yar999** [comment]
非常感谢,可以了.
