### ISSUE TITLE
关于使用嵌入预编辑/单行模式出现的问题

### ISSUE THREAD

**Issue by PygmalionDZ** [fcitx/fcitx5-rime#19]
在同时使用使用Fcitx5-Material-Color 皮肤的单行模式功能时（就是configtool里面的嵌入预编辑，快捷键ctrl-alt-p的那个），在部分网页中（如网页版onenote）点击“ctrl”键会直接导致被选中的部分被清除（故而影响ctrl-c等组合键的使用，因为在打出c之前，选中部分就被清掉了）关闭嵌入预编辑功能后问题解决，但无法使用单行模式

**Comment by wengxt** [comment]
不就应该这样吗？这是预期中的行为。
