### ISSUE TITLE
[Feature Repuest] 关于 fcitx5-Rime的候选词索引格式

### ISSUE THREAD

**Issue by hosxy** [fcitx/fcitx5-rime#2]
感觉fcitx5-rime的候选词索引格式不大好，候选词索引的数字直接和候选词挨在一起了，看着好奇怪，而 fcitx5 自带拼音格式就不错 `1. `，感觉这样视觉效果会好很多，如图：

![图片](https://user-images.githubusercontent.com/17108640/68638938-0c423c00-053e-11ea-91f2-6f5b52507a23.png)

![图片](https://user-images.githubusercontent.com/17108640/68638901-f03e9a80-053d-11ea-90db-f63201137f0c.png)

**Comment by wengxt** [comment]
An additional space is added.
