### ISSUE TITLE
嵌入编辑时候选位置

### ISSUE THREAD

**Issue by yueduz** [fcitx/fcitx5-rime#20]
fcitx5 在所有软件跟随的位置都在待提交文本的前面。
![2021-01-13 21-36-16 的屏幕截图](https://user-images.githubusercontent.com/1448159/104459402-a5a82a80-55e7-11eb-86ea-ab28f7388838.png)

fcitx5-rime 在 gedit 软件中候选栏跟随位置在待提交文本的末尾，在火狐中跟随位置在待提交文本的前面。
![2021-01-13 21-37-51 的屏幕截图](https://user-images.githubusercontent.com/1448159/104459504-c6708000-55e7-11eb-9937-a77c45f25c64.png)

**Comment by wengxt** [comment]
首先 gedit 和 firefox 的区别纯粹是程序自己的问题，这个我们控制不了

其次 rime 主要是因为你在设置了那个关于预编辑的选项，因为 rime 可以移动预编辑的光标，所以我必须设置真实的光标在，你把拼音也设置成程序中显示预编辑就变成和 rime 差不多了
