### ISSUE TITLE
使用 fcitx5-rime 在 chrome 输入框中键入 `bangdin` 触发 chrome 无响应

### ISSUE THREAD

**Issue by brsvh** [fcitx/fcitx5-rime#21]
具体现象如标题所述。

![image](https://user-images.githubusercontent.com/63050399/104811693-3ecd8000-5838-11eb-9231-c73bed97ff7b.png)

个人好奇是不是这个奇怪的联想字符导致的。

distro: ArchLinux
fcitx version: 5.0.4
fcitx-rime version: 5.0.3
Chrome version: Google Chrome 87.0.4280.141

**Comment by wengxt** [comment]
88.0.4324.96-1

无法重现你的问题

**Comment by brsvh** [comment]
好滴，辛苦
