### ISSUE TITLE
无法获取 fcitx5-rime 切换输入状态信息

### ISSUE THREAD

**Issue by 2014CAIS01** [fcitx/fcitx5-rime#22]
根据 https://github.com/fcitx/fcitx5-rime/issues/13 和 https://github.com/fcitx/fcitx5-rime/issues/15 中的描述，我将 fcitx5 的 shift 切换输入法的快捷键关闭，并由 rime 接管来临时切换中英文。但即使我在 fcitx5 的设置中打开了“切换输入法时显示输入法信息” 也并不能给我输入状态由中文切换成英文的反馈，因为它并不觉得我切换了输入法。

- fcitx5 设置快捷键，rime 关闭相关冲突的快捷键，打开键盘和 rime，使用 shift 临时切换，可以正确得到输入法切换的反馈。
- fcitx5 不设置快捷键，由 rime 接管，只打开 rime 输入法，使用 shift 临时切换，没有图标的反馈，只能自己打一下确认输入状态。

**Comment by syimyuzya** [comment]
不僅如此，用 Ctrl-Shift-3/4/5 等切換全半角、簡體輸出等選項時也沒有提示。（而 ibus 版、macOS 的鼠鬚管都有提示，甚至連 Windows 的小狼毫都有）

**Comment by wengxt** [comment]
@syimyuzya 没见到 ibus 有，请截图。

**Comment by syimyuzya** [comment]
> @syimyuzya 没见到 ibus 有，请截图。

……所以 iBus 版現在也沒提示了是麼。。（上次用 iBus 還是 2015 年 :joy: 鼠鬚管和小狼毫倒是今年都用過

**Comment by wengxt** [comment]
https://github.com/fcitx/fcitx5-rime/commit/ef24d41d7aada844b3367fdae2779ae9cb18961c
加了一个改变模式时显示。
