### ISSUE TITLE
Keyboard repeat doesn't work in Firefox in latin mode

### ISSUE THREAD

**Issue by ibertchen** [fcitx/fcitx5-rime#23]
When rime is in Latin mode, the keyboard repeat function doesn't work. For example, no matter how long I push a key, there will be only one character inputted. This problem does not happen in other browsers such as Brave.

**Comment by wengxt** [comment]
To my knowledge, your problem is that you are using xim instead of fcitx's gtk im module.
Please check fcitx5-diagnose output and set GTK_IM_MODULE correctly.

**Comment by ibertchen** [comment]
@wengxt Thank you.  It works now.  :smiley:
