### ISSUE TITLE
使用中遇到Meta(Win)键上屏的疑问

### ISSUE THREAD

**Issue by YLXDXX** [fcitx/fcitx5-rime#27]
设置了Meta键+其它键的快捷方式，在文本框内输入法激活能打字的情况下无法正常调用，例如按住Meta+a键，跟正常打字一样会出来候选词，然后才是启动相应快捷键绑定的脚本。这会造成很大的困扰，例如需要对选定的文字进行处理时会进行输入覆盖选定的文字。以前需要在中文中输入大写匹配时可以使用shift键辅助，在英文状态下可直接用shift大写上屏，现在即使在英文状态下使用Meta键也会启用中文的输入框。

这里的快捷键设定对于系统预设的没有任何冲突，直接调用，例如Meta+D返回桌面。利用kde系统内的快捷键设定调用也没有任何问题。但是通过Autokey来设定的各种快捷键有问题。

Meta在输入中充当了新角色，不知道是rime的新特性还是fcitx5的新特性，或者说是个执行侦测顺序的BUG？

**Comment by wengxt** [comment]
不太明白你什么意思，你按 meta +a 期待是啥行为实际是啥行为？

**Comment by YLXDXX** [comment]
按mate+a键：期待的行为是直接执行我绑定的脚本，在文本输入框内不产生任何影响；实际的行为是产生直接打字输入a的效果，再执行该快捷键绑定的脚本。


与之前的使用fcitx～rime的变化是：以前按住mate键输入不产生任何效果，无法输入，现在按住mate键可以进行正常的输入（中文下）。
&nbsp;

------------------ 原始邮件 ------------------
发件人: Weng Xuetian ***@***.***&gt;
发送时间: 2021年4月1日 22:24
收件人: fcitx/fcitx5-rime ***@***.***&gt;
抄送: YLXDXX ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[fcitx/fcitx5-rime] 使用中遇到Meta(Win)键上屏的疑问 (#27)





 
不太明白你什么意思，你按 meta +a 期待是啥行为实际是啥行为？

**Comment by wengxt** [comment]
FYI: https://github.com/fcitx/fcitx5-rime/issues/12
是 fcitx 正确识别了 super 并且发送给 rime。老的 fcitx-rime 里面这个反而是个 bug 否则就无法实别 rime 里面配置的 super

应该让 rime 在 engine 里面忽略。
https://github.com/rime/ibus-rime/commit/33b2755fbdacfad00fb1edec97174c55e04f748f#commitcomment-42303652

**Comment by zhenhua-wang** [comment]
> 应该让 rime 在 engine 里面忽略。

请问如何在engine忽略所有meta修饰过的按键？我也不希望按 meta +a 时继续输入文本。我更希望像以前一样，“按住mate键输入不产生任何效果，无法输入”。
