### ISSUE TITLE
动态加载lua插件

### ISSUE THREAD

**Issue by ZhiyuanLck** [fcitx/fcitx5-rime#29]
源码中似乎是在[`FCITX_INSTALL_LIBDIR`](https://github.com/fcitx/fcitx5-rime/blob/b022f4700403662b757d8ad63df1b3520dc0ffd6/src/rimeengine.cpp#L212)下查找 rime 的插件，比如在 `/usr/lib` 下查找` librime-lua.so`，而不是在 `/usr/lib/rime-plugins` 下查找，导致无法加载。将 `librime-lua.so` 复制到 `/usr/lib` 下，lua脚本中使用 `rime_api` 则会报错 `attempt to index a nil value (global 'rime_api')`

**Comment by wengxt** [comment]
rime 1.7.0 已经修改成由它自己加载插件了。那段代码只会在较老的 rime 上使用。你可能需要 rebuild 一下 fcitx5-rime
