### ISSUE TITLE
请问 fcitx5-rime 有没有切换中英文的命令

### ISSUE THREAD

**Issue by kekeimiku** [fcitx/fcitx5-rime#30]
想通过命令行切换中英文输入，因为使用emacs的时候需要一些行为需要自动切换成英文状态，，`fcitx5-remote` 似乎只能切换输入法而不是切换rime的中英文，，，

**Comment by wengxt** [comment]
没有。

**Comment by haolian9** [comment]
我有个比较迂回的办法： 
1. schema.custom.yaml 中设置 `{accept: "ctrl+shift+6", set_option: ascii_mode, when: always}`
2. 在fcitx lua addon 中通过一些机制，比如 watchEvent，触发中英文切换的动作： `os.popen('xdotool key ctrl+shift+6'`

不过目前我卡在 set_option 不能如预期工作，还在gitter中询问。

由于你使用emacs，或许这个 [issue](https://github.com/rime/librime/issues/354) 对你有所帮助

**Comment by QiangF** [comment]
@wengxt 大师有没有办法让emacs-rime和fcitx5-rime共用一套个人配置，个人词库？

**Comment by wengxt** [comment]
@QiangF ……你有问题不应该随便找个 issue 就回复……
1、emacs 用 fcitx 不行吗？推荐 pgtk 分支
2、rime 不知是否支持同时多个进程访问，如果可以你可以就设置成同一个路径或者ln 一下
3、如果都不行，那用 rime 自己的同步工具保持同步

**Comment by wengxt** [comment]
当然，我上面说的没有，并不是指没有办法实现，就是单纯想说没有实现

**Comment by QiangF** [comment]
我弄了一个fcitx5的emacs下系统输入法自动切换，目前感觉良好 https://github.com/QiangF/imbot

**Comment by wengxt** [comment]
$ qdbus org.fcitx.Fcitx5 /rime 
method QString org.fcitx.Fcitx.Rime1.GetCurrentSchema()
method bool org.fcitx.Fcitx.Rime1.IsAsciiMode()
method QStringList org.fcitx.Fcitx.Rime1.ListAllSchemas()
method void org.fcitx.Fcitx.Rime1.SetAsciiMode(bool)
method void org.fcitx.Fcitx.Rime1.SetSchema(QString)

增加一個 dbus 服務

**Comment by haolian9** [comment]
得益于作者增加的 dbus 服务，可以轻松地实现切换到 ascii mode： `busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b 1`
