### ISSUE TITLE
Inputmethod special layout cannot be applied.

### ISSUE THREAD

**Issue by Vonfry** [fcitx/fcitx5-rime#31]
My global keyboard layout is dvp, and I want to use qwerty for rime.

I use `fcitx5-config-qt` to add fcitx5-rime and set its keyboard layout. However, it doesn't affect rime. It also use my system keyboard layout.

If I use `fcitx5-config-qt` to set system keyboard layout, rime can use the selected one. By the way, other methods, such as mozc and wubi, can work with special layout for themselves.

Is this a bug? 

fcitx5 version: 5.0.4

**Comment by wengxt** [comment]
Your fcitx seems to be a little bit old. I think your problem should be fixed after fcitx 5.0.6.
