### ISSUE TITLE
Page size setting not working

### ISSUE THREAD

**Issue by GreenYun** [fcitx/fcitx5-rime#32]
I am running Arch Linux with Gnome and fcitx5-rime installed. After changing page size settings in both Fcitx5 Configuration and rime's default.yaml, and redeploying all, nothing about the page size changed. Is there effective way to make the page size larger?

**Comment by wengxt** [comment]
You need to make change to rime's yaml file, which is located under ~/.local/share/fcitx5/rime, see rime wiki for further reference.

https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%AF%8F%E9%A0%81%E5%80%99%E9%81%B8%E6%95%B8

**Comment by GreenYun** [comment]
I have already done write config to default.custom.yaml, and even tried to change default.yaml directly. But not working.

**Comment by xing2387** [comment]
> I have already done write config to default.custom.yaml, and even tried to change default.yaml directly, both in my ~/.local/share/fcitx5/rime folder. But not working.

in case who has the same problem. 
this need : 
1. create a new yaml config file. example:  ~/.local/share/fcitx5/rime/default.custom.yaml . 
2. then input:
    ```
    patch:
      "menu/page_size": 9
    ```
3. click deploy option to reload config

**Comment by dezbracaty** [comment]
> 

This not work , I change this option in default.yaml and default.custom.yaml , but  this not work.

**Comment by alon1996** [comment]
> > 
> 
> This not work , I change this option in default.yaml and default.custom.yaml , but this not work.

You can try to edit it in `/usr/share/rime-data`, it works for me.
