### ISSUE TITLE
有没有办法使用命令行得知rime正在使用什么schema

### ISSUE THREAD

**Issue by RRRRRm** [fcitx/fcitx5-rime#34]
正在写一个polybar脚本, 需要从脚本里获取输入法的状态

我可以通过 `dbus-send --session --print-reply --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.CurrentInputMethod` 得知Fcitx5正在使用什么输入法, 不知道有没有类似的方法可以知道rime正在使用什么schema

**Comment by chenshijie-uos** [comment]
我不是特别懂，rime的schema代表的什么意思。

**Comment by RRRRRm** [comment]
> 我不是特别懂，rime的schema代表的什么意思。
> 但是听rime讨论群里面的讨论信息。
> 具体操作应该是需要，向 https://github.com/rime/librime 项目提交代码，
> 然后再向fcitx5-rime里面添加对应的dbus接口，这样就可以获取到信息了

了解

**Comment by xingwozhonghua** [comment]
https://github.com/rime/librime/blob/23a8ae38fd4d570ae2b25e145d4485044a43fbb9/src/rime_api.h#L452
刚刚群里讨论说librime存在接口的,理论上在这个仓库里面添加dbus服务应该可以实现该功能.

**Comment by haolian9** [comment]
作者已经加入了对应的 dbus 服务, [见comment](https://github.com/fcitx/fcitx5-rime/issues/30#issuecomment-957001110)
