### ISSUE TITLE
设置编辑时候选框位置不跟随边框

### ISSUE THREAD

**Issue by solly0880** [fcitx/fcitx5-rime#35]
当前用的是fcitx5+rime ,当前rime的输入框是跟随光标的。下面这种效果：

![image](https://user-images.githubusercontent.com/56422293/131225808-66aab5fb-a72a-4d32-80f6-a8b9d9d971e1.png)

想要的是这种效果：
![image](https://user-images.githubusercontent.com/56422293/131225815-bd44d823-344b-46aa-b878-111a18268e96.png)

想问下。能不能通过配置实现呐。

**Comment by wengxt** [comment]
不能。
![图片](https://user-images.githubusercontent.com/259684/134713749-7333d1f1-f8b1-4f90-ac2d-8defc4590062.png)
最有可能的只有这样，但是这样就无法正确显示光标位置了

**Comment by wengxt** [comment]
最新的应该已经修改了，你可以试试
