### ISSUE TITLE
Switching IM to Rime shows 'Rime (not available)'

### ISSUE THREAD

**Issue by nlpsuge** [fcitx/fcitx5-rime#36]
Hi,

Rime is not available when switching to rime by  pressing Ctrl+Space

Run `fcitx5-diagnose`, I found some useful info:

3.  Addon Libraries:

    **Cannot find following required libraries for `rime` of addon `Rime`.**

        libboost_filesystem.so.1.69.0
        libboost_regex.so.1.69.0
        libboost_system.so.1.69.0
        libboost_locale.so.1.69.0
        libopencc.so.2

Os I use:
Fedora 40

I have boost-1.75 and its sub-packages installed.

Tried to install boost-system-1.69 but this will break the dependencies.

Tried `ln -s /usr/lib64/libboost_locale.so /usr/lib64/libboost_locale.so.1.69.0` but fcitx5 cannot be launched any more. 

I have opencc-1.1.1 installed. `ln -s /usr/lib64/libopencc.so /usr/lib64/libopencc.so.2` seems works.

Any advice?

**Comment by wengxt** [comment]
Your packages are broken. Either need to recompile for distro like gentoo, or you need to report bug to your packager.
