### ISSUE TITLE
libyaml-cpp更新了版本号

### ISSUE THREAD

**Issue by hansixue** [fcitx/fcitx5-rime#37]
更新了一下arch，似乎因为libyaml-cpp更新了版本号（0.6=》0.7）导致找不到文件，rime起不来了。
报错如下
E2021-11-02 06:31:38.093539 addonloader.cpp:34] Failed to load library for addon rime on /usr/lib/fcitx5/rime.so. Error: libyaml-cpp.so.0.6: cannot open shared object file: No such file or directory

**Comment by wengxt** [comment]
如果是你自己编译的，请自己编译，如果是官方包，请报给 Arch。fcitx-rime 没有直接调用 libyaml-cpp 的地方，都是 librime 自己调用的。
