### ISSUE TITLE
Blinking UI when typing on preedit enabled under Wayland

### ISSUE THREAD

**Issue by outloudvi** [fcitx/fcitx5-rime#38]
Reproduction steps:

* Run `QT_QPA_PLATFORM=wayland telegram-desktop`, and enable preedit, the UI will disappear and then display (i.e. blink) when typing

Other info:

* It does not happen on `QT_QPA_PLATFORM=xcb telegram-desktop` under Wayland
* It does not happen under X Server
* It does not happen when preedit is disabled

**Comment by wengxt** [comment]
Ok, origianlly I worry about the mismatch of highlight and cursor in rime, but after reading the code in librime, cursor_pos and sel_end is very likely to match with each other, so we can rely on highlight to show the actual cursor position.

**Comment by wengxt** [comment]
Added an new option to fix the cursor position.

**Comment by outloudvi** [comment]
Can confirm 332e478a9e4ef7bb4d2a87cd56c11047b11d2f63 provides a fix with `PreeditCursorPositionAtBeginning=True`, thanks!
