### ISSUE TITLE
请问 fcitx5-rime 有没有同步的命令

### ISSUE THREAD

**Issue by astroshot** [fcitx/fcitx5-rime#39]
RT，weasel、 squirrel 和安卓上的 trime 都有同步词库的命令，问下 fcitx5-rime 有吗？找了很久都没有找到 😭
没有界面的话，有命令行也行，先谢谢了 🙏

**Comment by wengxt** [comment]
![图片](https://user-images.githubusercontent.com/259684/146120808-00f20a18-1728-49ef-8dc8-45a25c8cef1d.png)

**Comment by nkta3m** [comment]
如果命令行该怎么写呢？想弄一个自动同步的脚本

**Comment by astroshot** [comment]
> ![图片](https://user-images.githubusercontent.com/259684/146120808-00f20a18-1728-49ef-8dc8-45a25c8cef1d.png)

我去年提这个 issure 的时候，操作系统和桌面环境是  manjaro + xfce，当时点键盘图标无法弹出这个界面，后来几次滚动升级后就有了，那会儿有些私事忙忘了回这个，现在对我来说，解决了我的问题。

> 如果命令行该怎么写呢？想弄一个自动同步的脚本

命令行可能不支持，但是点击「同步」按钮就可以实现词库的导出和备份
