### ISSUE TITLE
请问linux 下支持“针对特定程序使用英文模式”功能吗？

### ISSUE THREAD

**Issue by tankb52** [fcitx/fcitx5-rime#40]
就是以下配置，在windows 下面是可以的。
在 fcitx5-rime 上支持吗？
另外 Linux下的程序名，如givm应该怎么获取呢？
```
    # "app_options/gvim.exe":
    #     ascii_mode: true
```

**Comment by wengxt** [comment]
你可以试试 master，把 app_options 写到  ~/.local/share/fcitx5/rime/fcitx5.custom.yaml

Fcitx5 获取到的程序名称可以用这个命令查看 dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo

**Comment by wengxt** [comment]
Group [x11::0] has 1 InputContext(s)
  IC [dbf44643b1824b14b84f4d15da3da927] program:kwrite frontend:dbus cap:6000800072 focus:0
Input Context without group


例如这个就表示有一个 kwrite 连接到了 fcitx

当然这个是有限制的，不一定所有的 frontend 都能获得/获得正确的名字
用 im module 的 gtk/qt 程序可以，xim 如果程序设置了 pid 在 x property 上也可以，wayland 输入法协议不可以

**Comment by tankb52** [comment]
好的， 这个功能我测试在5.0.13上已经实现了。
先前没有留意，原来配置文件要写在 ~/.local/share/fcitx5/rime/fcitx5.custom.yaml 里面。

**Comment by jiacai2050** [comment]
> Group [x11::0] has 1 InputContext(s) IC [dbf44643b1824b14b84f4d15da3da927] program:kwrite frontend:dbus cap:6000800072 focus:0 Input Context without group
> 
> 例如这个就表示有一个 kwrite 连接到了 fcitx
> 
> 当然这个是有限制的，不一定所有的 frontend 都能获得/获得正确的名字 用 im module 的 gtk/qt 程序可以，xim 如果程序设置了 pid 在 x property 上也可以，wayland 输入法协议不可以

现在 ubuntu 26.04、debian 13 都已经切到 wayland 上了，是说没法支持 app_options 了吗

**Comment by CoelacanthusHex** [comment]
> > Group [x11::0] has 1 InputContext(s) IC [dbf44643b1824b14b84f4d15da3da927] program:kwrite frontend:dbus cap:6000800072 focus:0 Input Context without group
> > 例如这个就表示有一个 kwrite 连接到了 fcitx
> > 当然这个是有限制的，不一定所有的 frontend 都能获得/获得正确的名字 用 im module 的 gtk/qt 程序可以，xim 如果程序设置了 pid 在 x property 上也可以，wayland 输入法协议不可以
> 
> 现在 ubuntu 26.04、debian 13 都已经切到 wayland 上了，是说没法支持 app_options 了吗

很久以前就支持了
https://github.com/fcitx/fcitx5/commit/e1416c18e75a6ae0d5f4e001daae30f4ad0b683b

**Comment by jiacai2050** [comment]
多谢指出！ @CoelacanthusHex 

那怎么查看 app name 呢？


```
$ dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
   Group [wayland:] has 3 InputContext(s)
  IC [48ee5ae4b5e04dae8b010fc33a780257] program: frontend:dbus cap:c001000032 focus:0
  IC [702c9c23ae6d4128ae944086f11394aa] program: frontend:ibus cap:52 focus:0
  IC [906c4412c4a4463ea6be467844361f0c] program: frontend:dbus cap:c001000032 focus:1
Group [x11::0] has 6 InputContext(s)
  IC [c9af3da0ce1643ed96bdf0efce8847de] program:emacs frontend:dbus cap:6000000032 focus:0
  IC [eb537c3a485c4b3eab9cfd20ce00f409] program:emacs-gtk frontend:xim cap:4000000000 focus:0
  IC [14e5ab18a3c84e5fb1a194224ec620f8] program:emacs-gtk frontend:xim cap:4000000000 focus:0
  IC [771e85cfdd944a458013a7a498c4bf42] program:emacs frontend:dbus cap:6000000032 focus:0
Input Context without group
```

我还有 zed 打开的，上面没有显示，wayland 里面的三组 program 都是空。我是 debian 13 + gnome 桌面

**Comment by CoelacanthusHex** [comment]
> 多谢指出！ [@CoelacanthusHex](https://github.com/CoelacanthusHex)
> 
> 那怎么查看 app name 呢？
> 
> ```
> $ dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
>    Group [wayland:] has 3 InputContext(s)
>   IC [48ee5ae4b5e04dae8b010fc33a780257] program: frontend:dbus cap:c001000032 focus:0
>   IC [702c9c23ae6d4128ae944086f11394aa] program: frontend:ibus cap:52 focus:0
>   IC [906c4412c4a4463ea6be467844361f0c] program: frontend:dbus cap:c001000032 focus:1
> Group [x11::0] has 6 InputContext(s)
>   IC [c9af3da0ce1643ed96bdf0efce8847de] program:emacs frontend:dbus cap:6000000032 focus:0
>   IC [eb537c3a485c4b3eab9cfd20ce00f409] program:emacs-gtk frontend:xim cap:4000000000 focus:0
>   IC [14e5ab18a3c84e5fb1a194224ec620f8] program:emacs-gtk frontend:xim cap:4000000000 focus:0
>   IC [771e85cfdd944a458013a7a498c4bf42] program:emacs frontend:dbus cap:6000000032 focus:0
> Input Context without group
> ```
> 
> 我还有 zed 打开的，上面没有显示，wayland 里面的三组 program 都是空。我是 debian 13 + gnome 桌面

很不幸，GNOME 并没有实现任何能获取 app id 的协议，不论是 Plesma windows management 还是 wlr foreign toplevel management。请给 GNOME 报 bug 让他们实现一个能获取激活窗口的 app id 的协议。

**Comment by wengxt** [comment]
其实你也不用费个功夫去gnome file bug反正他们也不会考虑的……

**Comment by jiacai2050** [comment]
再请教下，kde 桌面支持嘛？
