### ISSUE TITLE
It appears that multiple instances of rime are active at the same time

### ISSUE THREAD

**Issue by xsrvmy** [fcitx/fcitx5-rime#45]
It seems that there are several instances of rime that are active at the same time when depending on which application I am using. So in one application I am in English mode, and when I switch to another application I am in Chinese mode instead.

I am on sway wayland if that matters. Is there a fix to this?

**Comment by wengxt** [comment]
That's a feature(TM). Are you requesting a new feature then?

**Comment by xsrvmy** [comment]
Well if this is a feature then it sorta defeats the option of keeping the input method the same across different applications in fcitx5.

**Comment by xsrvmy** [comment]
Update on this: I can confirm this also occurs in X11.
