### ISSUE TITLE
No input schemas are availiable after installation.

### ISSUE THREAD

**Issue by qtheperfect** [fcitx/fcitx5-rime#47]
In my Ubuntu 20.04.1 where the ibus packages are purged totally and fcitx and fcitx-rime is installed properly, how ever, nothing is available in my ~/.config/fcitx/rime/build except the file "default.yaml".

Ｎｏ　ｃｈｉｎｅｓｅ　ｃａｎ　ｇｅｔ　ｉｎｐｕｔ　ａｎｄ　ｔｈｅ　ｏｎｌｙ　ｄｉｆｆｅｒｅｎｃｅ　ｉｓ　ｔｈａｔ　ａｌｌ　ｍｙ　Ｅｎｇｌｉｓｈ　ｃｈａｒａｃｔｏｒｓ　ａｒｅ　ｄｏｕｂｌｅ－ｓｉｚｅｄ　ｗｈｅｎ　Ｒｉｍｅ　ｉｎｐｕｔ　ｉｓ　ｏｎ．

I tried copying some schema files from another computer, the Error remains.

**Comment by TNTErick** [comment]
Same Problem here.

**Comment by wengxt** [comment]
this is fcitx5-rime.
