### ISSUE TITLE
suddenly it can not start...

### ISSUE THREAD

**Issue by vvlaw** [fcitx/fcitx5-rime#48]
# System Info:
1.  `uname -a`:

        Linux archlinux 6.0.3-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Mon, 24 Oct 2022 10:30:44 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	Arch
        Description:	Arch Linux
        Release:	rolling
        Codename:	n/a

3.  `lsb_release -d`:

        Description:	Arch Linux

4.  `/etc/lsb-release`:

        DISTRIB_ID="Arch"
        DISTRIB_RELEASE="rolling"
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="38;2;23;147;209"
        HOME_URL="https://archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
        LOGO=archlinux-logo

6.  Desktop Environment:

    Cannot determine desktop environment.

7.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='x11'

8.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY=''

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn", "", ""

3.  Locale:

    1.  All locales:

            C
            C.UTF-8
            en_US.utf8
            POSIX
            zh_CN.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/vvlaw

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/vvlaw/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/vvlaw/.config/fcitx5`).

5.  Current user:

    The script is run as vvlaw (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/usr/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.19`

3.  process:

    **Fcitx5 is not running.**
    **Please check the Configure link of your distribution in [Beginner's Guide](http://fcitx-im.org/wiki/Beginner%27s_Guide) for how to setup fcitx5 autostart.**

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/usr/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/usr/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    **XMODIFIERS is not set**

    **Please set environment variable XMODIFIERS to "@im=fcitx" using the tool your distribution provides or add `export XMODIFIERS=@im=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: XMODIFIERS](http://fcitx-im.org/wiki/Input_method_related_environment_variables#XMODIFIERS).**
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

2.  qt5 - `${QT_IM_MODULE}`:

    **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**

3.  Qt IM module files:

    Found fcitx5 im module for qt: `/usr/lib/qt/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcms/kcm_fcitx5.so`.
    Found fcitx5 qt5 module: `/usr/lib/fcitx5/qt5/libfcitx-quickphrase-editor5.so`.
    Found fcitx5 im module for qt6: `/usr/lib/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/office6/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    **Cannot find fcitx5 input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.33` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.34` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        Found fcitx5 im modules for gtk `3.24.34`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

        Found `gtk-query-immodules` for gtk `3.24.34` at `/usr/bin/gtk-query-immodules-3.0-32`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0-32 from gtk+-3.24.34

        **Failed to find fcitx5 in the output of `/usr/bin/gtk-query-immodules-3.0-32`**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.33` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.33

        Found fcitx5 im modules for gtk `2.24.33`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

    2.  gtk 3:

        Found immodules cache for gtk `3.24.34` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.34

        Found fcitx5 im modules for gtk `3.24.34`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx5.so"
            "fcitx" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"
            "fcitx5" "Fcitx5 (Flexible Input Method Framework5)" "fcitx5" "/usr/locale" "ja:ko:zh:*"

        Found immodules cache for gtk `3.24.34` at `/usr/lib32/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0-32 from gtk+-3.24.34

        **Failed to find fcitx5 in immodule cache at `/usr/lib32/gtk-3.0/3.0.0/immodules.cache`**

    3.  gtk 4:

        Found immodules cache for gtk `4` at `/usr/lib/gtk-4.0/4.0.0/immodules/giomodule.cache`.

        **Failed to find fcitx5 in immodule cache at `/usr/lib/gtk-4.0/4.0.0/immodules/giomodule.cache`**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/usr/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 27 enabled addons:

            Simplified and Traditional Chinese Translation 5.0.15
            Classic User Interface 5.0.19
            Clipboard 5.0.19
            Cloud Pinyin 5.0.15
            DBus 5.0.19
            DBus Frontend 5.0.19
            Emoji 5.0.19
            Fcitx4 Frontend 5.0.19
            Full width character 5.0.15
            IBus Frontend 5.0.19
            Input method selector 5.0.19
            Keyboard 5.0.19
            KDE Input Method Panel 5.0.19
            Status Notifier 5.0.19
            Notification 5.0.19
            Pinyin 5.0.15
            Extra Pinyin functionality 5.0.15
            Punctuation 5.0.15
            Quick Phrase 5.0.19
            Rime 5.0.14
            Spell 5.0.19
            Table 5.0.15
            Unicode 5.0.19
            Wayland 5.0.19
            Wayland Input method frontend 5.0.19
            XCB 5.0.19
            X Input Method Frontend 5.0.19

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/vvlaw/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=默认
        # Layout
        Default Layout=cn
        # Default Input Method
        DefaultIM=shuangpin

        [Groups/0/Items/0]
        # Name
        Name=shuangpin
        # Layout
        Layout=

        [GroupOrder]
        0=默认

# Log:
1.  `date`:

        Sun Oct 30 11:06:22 AM AEDT 2022

2.  `/home/vvlaw/.config/fcitx5/crash.log`:

    `/home/vvlaw/.config/fcitx5/crash.log` not found.

**Warning: the output of fcitx5-diagnose contains sensitive information, including the distribution name, kernel version, name of currently running programs, etc.**

**Though such information can be helpful to developers for diagnostic purpose, please double check and remove as necessary before posting it online publicly.**

**Comment by goduck777** [comment]
I think I got a similar issue. The latest fcitx5 will just crash when trying to load fcitx5-rime input method.

The log is like this
```
*** stack smashing detected ***: terminated
=========================
Fcitx 5.0.19 -- Get Signal No.: 6
Date: try "date -d @1667831270" if you are using GNU date ***
ProcessID: 1282958
fcitx5(+0xe48d)[0x55f3c047a48d]
/lib64/libc.so.6(+0x3daa0)[0x7f7945ae1aa0]
/lib64/libc.so.6(+0x8956c)[0x7f7945b2d56c]
/lib64/libc.so.6(raise+0x12)[0x7f7945ae1a02]
/lib64/libc.so.6(abort+0xcf)[0x7f7945acc469]
/lib64/libc.so.6(+0x7d888)[0x7f7945b21888]
/lib64/libc.so.6(__fortify_fail+0x22)[0x7f7945bbd5d2]
/lib64/libc.so.6(__fortify_fail+0x0)[0x7f7945bbd5b0]
/usr/lib64/rime-plugins/lua.so(+0x5ba34)[0x7f793456ca34]
/usr/lib64/librime.so.1(_ZN4rime13PluginManager11LoadPluginsEN5boost10filesystem4pathE+0x45b)[0x7f7934a1d09b]
/usr/lib64/librime.so.1(+0xe87c3)[0x7f7934a1d7c3]
/usr/lib64/librime.so.1(_ZN4rime11LoadModulesEPPKc+0x91)[0x7f7934a668f1]
/usr/lib64/librime.so.1(RimeInitialize+0x24)[0x7f7934a23b04]
/usr/lib64/fcitx5/rime.so(+0xcacd)[0x7f793c1b8acd]
/usr/lib64/fcitx5/rime.so(+0xe397)[0x7f793c1ba397]
/usr/lib64/fcitx5/rime.so(+0xf4bc)[0x7f793c1bb4bc]
/usr/lib64/fcitx5/rime.so(+0x131f0)[0x7f793c1bf1f0]
/usr/lib64/libFcitx5Core.so.7(+0x86651)[0x7f7946067651]
/usr/lib64/libFcitx5Core.so.7(+0x893bb)[0x7f794606a3bb]
/usr/lib64/libFcitx5Core.so.7(+0x89bff)[0x7f794606abff]
/usr/lib64/libFcitx5Core.so.7(_ZN5fcitx12AddonManager5addonERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0xff)[0x7f7946068b2f]
/usr/lib64/libFcitx5Core.so.7(_ZN5fcitx8Instance19activateInputMethodERNS_17InputContextEventE+0x288)[0x7f794602b718]
/usr/lib64/libFcitx5Core.so.7(_ZNK5fcitx8Instance9postEventERNS_5EventE+0x324)[0x7f794602a614]
/usr/lib64/libFcitx5Core.so.7(+0x4b07b)[0x7f794602c07b]
/usr/lib64/libFcitx5Core.so.7(_ZN5fcitx8Instance21setCurrentInputMethodEPNS_12InputContextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x249)[0x7f794602da29]
/usr/lib64/fcitx5/libnotificationitem.so(+0x2778f)[0x7f793e39278f]
/usr/lib64/libFcitx5Utils.so.2(+0x462d2)[0x7f7945f502d2]
/lib64/libsystemd.so.0(+0x7f1cc)[0x7f79459e41cc]
/lib64/libsystemd.so.0(sd_event_dispatch+0x11d)[0x7f79459e450d]
/lib64/libsystemd.so.0(sd_event_run+0xc0)[0x7f79459e4c70]
/lib64/libsystemd.so.0(sd_event_loop+0x57)[0x7f79459e4e87]
/usr/lib64/libFcitx5Utils.so.2(_ZN5fcitx9EventLoop4execEv+0x11)[0x7f7945f50441]
```

**Comment by wengxt** [comment]
@goduck777 your distro didn't compile fcitx5-lua in dlopen mode. 

What's your distro? Also the so name doesn't look similar to what arch have. So I'd guess some some your package is not up to date (at least your distro didn't provide a update to date version).

And your problem is not related to the original reporter.

**Comment by wengxt** [comment]
@vvlaw You problem is very likely due to arch remove pambase's user env support. Please use an alternative way to set environment variable. 

See also:
https://fcitx-im.org/wiki/Setup_Fcitx_5
https://wiki.archlinux.org/title/Environment_variablesa

**Comment by goduck777** [comment]
@wengxt Thank you for reminding me. I indeed did not install fcitx-lua (I didn't know because everything works well before without it). However, after I installed it with USE_DLOPEN (I think it is ON by default), I still got the same error.

I am using Gentoo. All my fcitx components, including fcitx-rime, fcitx-qt, are all from git. I am not sure about rime. Do I need to recompile all the rime after installing fcitx-lua?

**Comment by wengxt** [comment]
If you didn't install fcitx5-lua at all. Then it's not the issue that I'm thinking of. 
The issue I'm talking about is when rime + lua and fcitx5-lua are installed together but linked to different version of lua. That issue is intended to be solved with USE_DLOPEN option (and relies on dlmopen).

As for your issue, then I feel like it might be your rime configuration or rime itself need rebuild. If you don't use rime's lua at all, maybe consider disable it. Or your rime-lua is building with a old version of rime or whatever.

Because on arch, rime is loading plugin differently on itself and using a different file name for rime lua plugin.

**Comment by goduck777** [comment]
Thank you again. I recompile librime-lua and the problem is solved. It seems that this library should be recompiled when lua is upgraded but the package was not configured well.

I apologize as this is not a fcitx issue.

**Comment by wengxt** [comment]
Yeah. Every lua minor version is not binary compatible.
