### ISSUE TITLE
能否增加像 fcitx5-chinese-addons（fcitx5默认中文输入法）那样的笔画筛选功能

### ISSUE THREAD

**Issue by yilksd** [fcitx/fcitx5-rime#55]
fcitx5-chinese-addons 可以在按“`”之后对第一个字进行笔画筛选，具体规则为：h 横、s 竖、p 撇、n 捺、z 折 ，fcitx5-rime能不能也有这样的功能？

**Comment by CoelacanthusHex** [comment]
这个不是 fcitx5-rime 要实现的，是 librime 和具体的 Rime 输入方案要实现的。

**Comment by wengxt** [comment]
请在 librime那边寻找解决方案
