### ISSUE TITLE
no automatic syncing

### ISSUE THREAD

**Issue by ChengYuShun** [fcitx/fcitx5-rime#56]
It seems that currently fcitx5-rime won't synchronize unless the user clicks the button manually. This will make the history of the current session inaccessible once fcitx5 stops, and therefore causing a lot of inconvenience.

# Steps to Reproduce

- type a rare character that you've never typed before
- retype it, and notice that it appears immediately without having to scroll down the list
- restart fcitx5
- type the character again, and you will have to scroll down the list to find it again!

# Possible Solutions

One thing that I've tried is to make fcitx5-rime to call `sync()` method whenever it stops:

```diff
--- a/src/rimeengine.cpp
+++ b/src/rimeengine.cpp
@@ -141,6 +141,7 @@ RimeEngine::RimeEngine(Instance *instance)
 }

 RimeEngine::~RimeEngine() {
+    sync();
     factory_.unregister();
     try {
         if (api_) {
```

It seems to be working so far, but since I am not familiar with the structure of fcitx5, it might actually be a bad patch.

I think it would also be helpful if synchronization could be done in command line, although I don't know if it is possible to implement that way.

**Comment by c02y** [comment]
That's great, I need this feature, or at least an option can be provided.

the command line part to sync is:
```
qdbus org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.SetConfig fcitx://config/addon/rime/sync ''
```
reference: https://github.com/fcitx/fcitx5-rime/issues/54#issuecomment-1491312366

But it is a little complicated.
