### ISSUE TITLE
Appearance settings in fcitx5-rime on Arch Linux have no effect

### ISSUE THREAD

**Issue by zhaoxian-afra** [fcitx/fcitx5-rime#58]
Description:

I am currently using fcitx5-rime on Arch Linux, and I am able to change the appearance settings in the "Classic User Interface". However, regardless of the settings I choose, the windows continue to display with the font size and font type that I previously modified them to display with (I had modified them to display with larger font size and different font type). I am unable to adjust the font size or change the font type to my desired settings.

I have also tried changing the desktop environment from KDE to GNOME, but I still cannot modify the appearance settings in fcitx5-rime.

Steps to reproduce:

    Install fcitx5-rime on Arch Linux.
    Launch fcitx5-rime and switch to the "Classic User Interface".
    Change the appearance settings for the input method window or the candidate window.
    Notice that the windows continue to display with the font size and font type that were previously modified, regardless of the settings you choose.

Expected result:

The appearance settings I choose should be reflected in the appearance of the input method window and the candidate window in fcitx5-rime's "Classic User Interface".

Actual result:

The windows continue to display with the font size and font type that were previously modified, regardless of the settings I choose.

Environment:

    Arch Linux
    fcitx5-rime version:  latest
    Qt version:  latest
    fcitx5 version: latest
    Desktop environment: kde

Additional information:

I have already tried deleting fcitx5-rime's configuration files and restarting the application, but the issue persists. I have also tried reinstalling fcitx5-rime multiple times, but the issue remains. In addition, I have tried changing the desktop environment from KDE to GNOME, but the issue persists in both environments.

Please let me know if there are any further steps I can take to resolve this issue.

Thank you for your attention to this matter.

**Comment by wengxt** [comment]
Are you using any flatpak package?

**Comment by wengxt** [comment]
please reopen if you can still reproduce.

**Comment by fraxiinus** [comment]
I'm having this issue.

fcitx5: 5.1.10-1
fcitx5-rime: 5.1.8-1
kde: 6.1.3-1

```yml
patch:
  schema_list:
    - schema: bopomofo
  "style/font_face": "TW-Kai"
  "style/font_point": 32
  "menu/page_size": 9
```

No matter the value put in `font_point`, the selection menu font stays the same. I am able to change `page_size` and it works. Notice that the font specified "TW-Kai" is also not used.

![image](https://github.com/user-attachments/assets/4f13d113-a63d-470c-ba3e-b904d58e9ab2)
