### ISSUE TITLE
请问如何定制fcitx5-rime输入法？

### ISSUE THREAD

**Issue by zhengpushi** [fcitx/fcitx5-rime#61]
补充：我使用debian11.7的系统，安装输入法是 apt install fcitx5-rime。

由于rime有太多发行版本，ibus-xx, fcitx-xx, fcitx5-xx，网络上找到的参考资料也非常混乱。
我现在使用 fcitx5-rime，目前看到这个repo是原始仓库，但是没有看到供用户参考的详细说明文档。
我有几个问题想请教：
1. 该输入法的配置文件在哪里，以及如何使用？
2. 如何定义每页的选择项数目从5修改到9？
3. 如果上述修改是直接编辑某个配置文件，请问如何“部署”？我的系统上没有fcitx5的图标，没有“部署”按钮，如何在命令行下实现，是 rime_deployer 命令吗？
4. 如何导入和导出词库？

**Comment by wengxt** [comment]
路径是 ~/.local/share/fcitx5/rime

**Comment by zhengpushi** [comment]
> 路径是 ~/.local/share/fcitx5/rime
感谢。
我还想再请教，当我参考了网络上的一些文档后，
在该目录写入 default.custom.yaml 文件，内容为
```
patch:
  "menu/page_size": 8
```
然后使用 `$ rime_deployer --build ~/.local/share/fcitx5/rime /usr/share/rime-data` 命令来部署，但是没有效果。请问是配置文件不正确吗？还是部署命令不正确？有没有一个推荐的 fcitx5-rime 的文档？

**Comment by wengxt** [comment]
切换到rime之后从托盘图标找重新部署即可
