### ISSUE TITLE
Sometimes I cannot switch the rime methods,but if I restart the fcitx5,it will be fixed.

### ISSUE THREAD

**Issue by kamikaze211** [fcitx/fcitx5-rime#63]
I have installed several input methods by fcitx5.
I can switch to Japanese mozc, and have no issue.
But sometimes I switch to Chinese rime, then I cannot input any Chinese words.
But I tried to restart fcitx5, then the problem will be fixed.

I set a hotkey (ctrl+alt+f) to run this command: killall -9 fcitx5 ; fcitx5
It works fine, but I don't know if it is a bug, or just happened on my pc.

Here is the info printed by fastfetch:

OS: Arch Linux x86_64
Kernel: 6.4.11-zen2-1.1-zen
Uptime: 1 hour, 19 mins
Packages: 1952 (pacman)
Shell: bash 5.1.16
Display: 3440x1440 @ 165Hz
DE: KDE Plasma 5.27.7
WM: KWin (Wayland)
WM Theme: Lavanda-Dark
Theme: kvantum-dark (LavandaDark) [QT], Materia-dark-compact [GTK2/3/4]
Icons: Colloid-pink-dark [QT], Colloid-pink-dark [GTK2/3/4]
Font: 更纱黑体 SC (16pt) [QT], 更纱黑体 SC (16pt) [GTK2/3/4]
Cursor: WhiteSur (36px)
Terminal: konsole 23.4.3
Terminal Font: Monospace (22pt)
CPU: 12th Gen Intel(R) Core(TM) i5-12400 (12) @ 4.4 GHz
GPU 1: Intel UHD Graphics 730
GPU 2: AMD Radeon RX 6600 XT
Memory: 7.04 GiB / 31.06 GiB (22%)
Disk (/): 56.98 GiB / 196 GiB (29%)
Disk (/home): 707 GiB / 2 TiB (41%)
Disk (/run/media/zzy/HDD2): 1 TiB / 2 TiB (61%)
Disk (/run/media/zzy/Recovery): 282 GiB / 932 GiB (30%)
Locale: en_US.UTF-8

**Comment by wengxt** [comment]
@kamikaze211 https://github.com/fcitx/fcitx5-rime/commit/143cff9fc69e193dc83baa04019e80ba23820046

**Comment by kamikaze211** [comment]
> @kamikaze211 [143cff9](https://github.com/fcitx/fcitx5-rime/commit/143cff9fc69e193dc83baa04019e80ba23820046)

Thank you for reply.
You mean that we can wait for the new version that can fix this bug?

**Comment by hsingko** [comment]
It happened on my arch too since yesterday, so I rollback to 5.0.16-1

**Comment by wengxt** [comment]
fixed in 5.1.1

**Comment by kamikaze211** [comment]
> fixed in 5.1.1

Oh , many thanks !

**Comment by wengxt** [comment]
@Vonfry tarball is uploaded anyway
