### ISSUE TITLE
如何在所有程序中共享输入状态

### ISSUE THREAD

**Issue by tbontb-iaq** [fcitx/fcitx5-rime#64]
在 fcitx5 的配置面板中设置了共享输入状态，但是在 rime 里还是会记住每个窗口的输入状态。
![image](https://github.com/fcitx/fcitx5-rime/assets/33752432/943ade7e-8dcc-4126-b169-a26c3fe5f447)
![Peek 2023-08-20 21-59](https://github.com/fcitx/fcitx5-rime/assets/33752432/66a12523-2933-4cb0-86a8-493c0e03e986)

**Comment by wengxt** [comment]
fixed in latest version .
