### ISSUE TITLE
[简单记录一下] 似乎在 flatpak应用 里产出的所有字词都会进入 clipboard ?

### ISSUE THREAD

**Issue by Binly42** [fcitx/fcitx5-rime#69]
不管是 正常空格上档中文, 还是 enter直接上档, 都会如此;
但如果乖乖退格删掉就没事;

用 英文模式 无此现象;
我新建了一个 `Group` 然后添加 `Shuangpin`, 试了也没事;

在其他地方也都没事, 试过:
- firefox-esr
- kate
- start菜单

目前发现就是 flatpak应用 里会出现, 试过:
- net.agalwood.Motrix 1.8.15
- com.visualstudio.code 1.76.2-1678817801

---

env:
- os: debian 11.7 stable kde 5.20.5
- clipboard: klipper 5.20.5
- fcitx5-rime: 5.0.4-1

---

这里先纯做个记录, 有时间的话我可能再琢磨下...

**Comment by wengxt** [comment]
是chrome的问题

他们时不时就会搞坏一次

类似这个 https://bugs.chromium.org/p/chromium/issues/detail?id=1213325

如果最新还有问题建议报给chrome或者electron

**Comment by Binly42** [comment]
原来如此, 太骚了...

---

倒是我刚还发现: 原来居然连输入法都不用打开, 选中的任意文本都会被记录, 而且这种现象还稳定复现于我主楼所提及的所有程序里 ...

那这次说不定就不是chrome的问题了, 不过反正也跟 fcitx5-rime 这边没啥关系 ~
