### ISSUE TITLE
重新部署或者重载配置后未返回原先在用方案

### ISSUE THREAD

**Issue by fxliang** [fcitx/fcitx5-rime#76]
使用带Rime插件的fcitx-android, 重新部署或者重载配置，会无法返回之前在用的方案。检查user.yaml文件发现未写入previously_selected_schema等相关信息用于恢复状态，盼修复😀
1012更新下
似乎原因是f5a崩了的原因，部署或者重载配置必崩，时不时崩

补充截屏

https://github.com/fcitx/fcitx5-rime/assets/4023160/42a139d6-9d31-4519-87df-ffad6e589718

**Comment by eagleoflqj** [comment]
librime 切换方案有两种方法：方案选单和RimeSelectSchema API。
经查是方案选单修改了user_config，并在Switcher析构时写入FS；而API无此操作。
https://github.com/rime/librime/pull/736 已将修改user_config的操作下移一层，这样两种方法都可以写入FS了。
