### ISSUE TITLE
当 commit_code 时，输入预览没有清空

### ISSUE THREAD

**Issue by Victrid** [fcitx/fcitx5-rime#83]
**描述错误**

当发出 commit_code 时，输入预览没有清空。

librime上的相同issue https://github.com/rime/librime/issues/761 指出这可能是一个fcitx5-rime的问题。因为在Arch Linux上，下文中的测试所使用的librime版本均为1.9.0。

**重现**
重现错误的步骤
1. 将`patch.ascii_composer.switch_key.Shift_L`设置为`commit_code`。
2. 输入内容，按 Shift_L 上屏并进入 ascii 模式
3. 输入预览区仍在显示，没有清空
4. 按下另一个键，输入的字符丢失

**预期行为**
不应继续显示输入预览。

**屏幕截图**

https://github.com/rime/librime/assets/39787044/1fefec74-2edd-4c77-a31f-0f19e3c4795a

软件包：
- 操作系统 Arch linux
- fcitx5-rime 版本： 5.1.3-1
- 桌面环境 KDE Plasma
- URI: https://archlinux.org/packages/extra/x86_64/fcitx5-rime/

**附加背景**
这可能是一个回归问题。这些软件包是从 Arch Linux 安装的，使用 librime 1:1.9.0-1。

| fcitx5 | fcitx5-rime | 有此问题？|
|---------|-------------|----------------------|
| 5.1.1-1 | 5.1.2-1 | 没有 | 
| 5.1.4-1 | 5.1.3-1 | 是 | 
| 5.1.5-1 | 5.1.3-1 | 是 | 

其他Issue https://github.com/fcitx/fcitx5-rime/issues/82 也提出类似现象但可能不相同的问题。~~如果是openSUSE Tumbleweed，则应该对应的是fcitx5-rime 5.1.2和librime 1.8.5。~~ 在该issue中，指出同样使用 fcitx-rime 5.1.3 / librime 1.9.0

**Comment by wengxt** [comment]
https://github.com/fcitx/fcitx5-rime/issues/82 

把预编辑选项修改一下。
因为改名的缘故选项可能重置了，导致触发了这个，但本质应该是librime的bug
