### ISSUE TITLE
有考虑加入win端和macos端的vim mode

### ISSUE THREAD

**Issue by newbie163** [fcitx/fcitx5-rime#84]
有考虑加入vim mode吗，想必rime的用户会和vim用户高度重合。并且在不同的app上都会使用vim模式。但总不可能在所有的app安装类似的插件，总有不支持的。

**Comment by wengxt** [comment]
@newbie163 第一，没有；第二，我不知道你说的这个功能什么意思；第三，这个功能即使实现恐怕也不是在fcitx5-rime层面实现

**Comment by newbie163** [comment]
好吧，vim mode就是退出vim的insert模式时候输入法切换为英文。

**Comment by wengxt** [comment]
https://github.com/lilydjwg/fcitx.vim

这不是一直有吗

**Comment by newbie163** [comment]
> https://github.com/lilydjwg/fcitx.vim
> 
> 这不是一直有吗

这是vim上的，因为多个应用使用vim模式都要配置一遍这个插件有点麻烦比如jb家和vsvode的vim模式，在或者浏览器上面的vimium等等用到vim模式的地方都需要。当然都可以通过各种途径解决，只是在输入法方面解决比较方便，既然不考虑的话我再找找别的路径解决，谢谢。（我去研究研究lua脚本说不定会有新发现）

**Comment by wengxt** [comment]
@newbie163 你有没有想过输入法根本不知道（也不可能知道）程序是不是在插入模式

特别是你的需求是那么多随机的程序实现的vim mode，他们更不可能有统一的方式汇报是否处于插入模式

我认为你的思路有问题，建议回去仔细想想

**Comment by newbie163** [comment]
好的，谢谢，我在想想

**Comment by lei4519** [comment]
实现了一个简易版的，全平台通用的逻辑，可以参考
https://github.com/lei4519/blog/issues/85
