### ISSUE TITLE
更新5.1.4后 arch linux kde 自定义任务栏图标不再生效

### ISSUE THREAD

**Issue by mingti** [fcitx/fcitx5-rime#88]
之前我使用 kde 自定义主题将rime英文状态下的任务栏图标一个大写的 "A"  替换为 "En" . 在更新了5.1.4以后,这种方法不在生效

我手动降级到5.1.3以后恢复正常, 请问在5.1.4我可以使用什么方式来更改图标?  

我具体做法为添加一个包含 id 为 "fcitx-rime-latin" 的svg对象的 "fcitx.svgz" 文件到"/home/dongka/.local/share/plasma/desktoptheme/breeze-dark-fcitx-rime/icons/"

![image](https://github.com/fcitx/fcitx5-rime/assets/24843766/6d5a124a-90b4-4ad9-8b8a-4aaa39276b2c)

fcitx.svgz
![image](https://github.com/fcitx/fcitx5-rime/assets/24843766/27084961-4fac-4456-8e29-31e6cc6eae2d)

breeze-dark-fcitx-rime是暗黑主题,  dafault是明亮主题. 区别主要为fcitx.svgz中颜色不一样.

方法来源于这里:https://develop.kde.org/docs/plasma/theme/theme-tray-icons/

**Comment by rocka** [comment]
试一下 `fcitx_rime_latin` ， 把 `-` 改成 `_`

https://github.com/fcitx/fcitx5-rime/commit/7ec7e8a375125b28ee13c563f8bf60b493534aab#diff-c662041f21fc059e2338e07a0bc4189e74d1af3e22d12e7c1640ec61436b1e31

**Comment by mingti** [comment]
> 试一下 `fcitx_rime_latin` ， 把 `-` 改成 `_`
> 
> [7ec7e8a#diff-c662041f21fc059e2338e07a0bc4189e74d1af3e22d12e7c1640ec61436b1e31](https://github.com/fcitx/fcitx5-rime/commit/7ec7e8a375125b28ee13c563f8bf60b493534aab#diff-c662041f21fc059e2338e07a0bc4189e74d1af3e22d12e7c1640ec61436b1e31)

我尝试了这样的做法, 但没有生效,我重启电脑并重新应用了主题

**Comment by wengxt** [comment]
@mingti 主要是图标名字变了

**Comment by wengxt** [comment]
@mingti 我推荐你用图标主题的方式覆盖，而不是plasma主题的，修改图标名字也是为了避免xdg规定的fallback规则产生副作用，放对应图标到 ~/.local/share/icons/breeze（或其他名字）/..... 应该就行

**Comment by mingti** [comment]
感谢各位, 我设置好了, 如下是我的配置:

 另想请问下,如果我选择直接覆盖`/usr/share/icons/hicolor/scalable/apps/org.fcitx.Fcitx5.fcitx_rime_latin.svg`,这样是不是每次fcitx5-rime更新, 我就需要再覆盖一次?

![image](https://github.com/fcitx/fcitx5-rime/assets/24843766/3298ca40-8b0d-4841-8f6a-8cd1be0dc660)




index.theme
```ini
[Icon Theme]
Name=fcitx_rime_latin_breeze_dark

Comment=fcitx_rime_latin_breeze_dark

#明亮主题这里将breeze-dark改成breeze
Inherits=breeze-dark,hicolor

FollowsColorScheme=true


KDE-Extensions=.svg

Directories=fcitx_rime_latin


[fcitx_rime_latin]
Size=48

```

**Comment by wengxt** [comment]
@mingti 是的

**Comment by mingti** [comment]
@wengxt 感谢解答, 另有一点点建议, 英文状态下的图标是一个大写的A, 第一感觉总是让人误以为开启了大写, 而不是处在英文状态, 是否考虑更换一个图标呢?
