### ISSUE TITLE
Infinite loop when the userdb is locked

### ISSUE THREAD

**Issue by ksqsf** [fcitx/fcitx5-rime#90]
When fcitx5-rime shares its rime user data with another rime implementation, they can compete for the userdb lock (`*.userdb/LOCK`). However, when fcitx5-rime cannot grab the lock, it loops forever, and becomes effectively unusable.

The culprit seems to be `updateAppOptions` releasing all sessions:

https://github.com/fcitx/fcitx5-rime/blob/15215dd68b04bbba25ca77bd47b9d65ad4a42982/src/rimeengine.cpp#L439

It is called by `notify`, after rime is deployed successfully:

https://github.com/fcitx/fcitx5-rime/blob/15215dd68b04bbba25ca77bd47b9d65ad4a42982/src/rimeengine.cpp#L659

It seems that fcitx5-rime assumes that after a successful deployment, rime will not deploy again.  However, this assumption is false: when the userdb is locked, rime will report success, but once it's restarted, it will try to deploy again, which leads to the infinite loop described above.

Removing the line `releaseAllSessions()` from `updateAppOptions()` fixes this problem, but I'm not sure if there are other deeper considerations. It's introduced in commit 27fbb97017406250b372a9a990e5de5da1a273e4.

**Comment by wengxt** [comment]
@ksqsf why would the data be shared with another rime implementation?

**Comment by ksqsf** [comment]
I created a symlink to share my user dir with Squirrel because it's quite big. I understand this may be unusual.

**Comment by ksqsf** [comment]
BTW It can be reproduced easily:

```
rm *.userdb/LOCK
touch luna_pinyin.userdb/LOCK
chmod 000 *.userdb/LOCK
sudo chown root *.userdb/LOCK
```

**Comment by wengxt** [comment]
I don't consider that's a supported use case, nor it should be fixed by fcitx5-rime.

**Comment by ksqsf** [comment]
> nor it should be fixed by fcitx5-rime

I read relevant parts of librime and I agree there's some truth to that: in `leveldb::RepairDB` reports repair success but actually the next open will fail. It's a bit unfortunate because it's nobody's fault: not leveldb's fault (it cannot guarantee sucessful open because of race conditions), not librime's fault (leveldb says ok), not fcitx5-rime's fault (librime says ok).

That being said, I'm still baffled why refreshing app options must kill existing sessions. Personally, I think it's totally acceptable to only apply new options to new input contexts. Am I missing something?

**Comment by wengxt** [comment]
@ksqsf app options need to be re-applied, also, since no new session can be created during maintainence, release all session is intended.
